<?php

namespace AppBundle\Repository;

/**
 * AbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbilityRepository extends \Doctrine\ORM\EntityRepository
{
}
