<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;
use AppBundle\Entity\Pokemon;
use AppBundle\Entity\Ability;
use AppBundle\Entity\Type;

/**
 * PokemonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends \Doctrine\ORM\EntityRepository
{
}
