<?php

namespace AppBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTeamByPokemonType(int $id){

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT t, p, tt 
                FROM AppBundle:Team t
                JOIN t.pokemon p
                JOIN p.type tt 
                WHERE tt.id = :id 
                ORDER BY t.id DESC'
        )->setParameter('id', $id);

        return $query->getResult();

    }

}
